modLoader = "javafml"
loaderVersion = "[38,)"
license = "MIT"
[[mods]]
modId = "minimotd"
version = "${file.jarVersion}"
displayName = "MiniMOTD"
displayURL="https://github.com/TomatoPuddin/MiniMOTD-forge"
authors="TomatoPuddin"
description = '''

'''

[[dependencies.minimotd]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.minimotd]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"
